model_params:
  name:                   'BetaVAE'
  in_channels:            3
  z_dim:                  64
  input_dim:              64
  # loss_type == 'H' (https://openreview.net/forum?id=Sy2fzU9gl)
  beta:                   10.0

train_params:
  batch_size:             128
  n_epochs:               150
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'beta_vae_h'
  log_interval:           5
  checkpoint_preload:     False
  generate_samples:       True
  use_tensorboard:        True