model_params:
  name:                   'BetaVAE'
  in_channels:            3
  z_dim:                  30
  input_dim:              64
  # loss_type == 'B' (https://arxiv.org/pdf/1804.03599.pdf)
  gamma:                  20.0
  C_max:                  13
  C_stop_iter:            80000

train_params:
  batch_size:             128
  n_epochs:               150
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'beta_vae_b'
  log_interval:           10
  checkpoint_preload:     False
  generate_samples:       True
  use_tensorboard:        True