model_params:
  name:                   'EndToEnd'
  in_channels:            3
  input_dim:              64

train_params:
  batch_size:             64
  n_epochs:               150
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'end_to_end'
  log_interval:           10
  checkpoint_preload:     False
  use_tensorboard:        True