model_params:
  name:                   'LatentNN'
  in_channels:            3
  # num_prvs:               0
  # prvs_mode:              'exponential' # {'exponential', 'linear'}
  with_yawRate:           False

train_params:
  batch_size:             256
  n_epochs:               150
  optimizer:
    type:                 'Adam'
    learning_rate:        0.001
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'latent_nn'
  log_interval:           10
  checkpoint_preload:     False
  use_tensorboard:        True