model_params:
  name:                   'LatentNN'
  in_channels:            3
  z_dim:                  30
  num_prvs:               5
  prvs_mode:              'linear' # {'exponential', 'linear'}

train_params:
  batch_size:             256
  n_epochs:               300
  optimizer:
    type:                 'Adam'
    learning_rate:        0.001
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'latent_nn_complex'
  log_interval:           5
  checkpoint_preload:     False
  use_tensorboard:        True