model_params:
  name:                   'VanillaVAE'
  in_channels:            3
  z_dim:                  64
  input_dim:              64

train_params:
  batch_size:             128
  n_epochs:               20
  optimizer:
    type:                 'Adam'
    learning_rate:        0.0005
    betas:                (0.9, 0.999)
    weight_decay:         0.0
  manual_seed:            1234

log_params:
  name:                   'vanilla_vae'
  log_interval:           5
  checkpoint_preload:     False
  generate_samples:       True
  use_tensorboard:        True