## Simulation parameters
sim_params:
  loop_rate:                  10.0 # Hz
  output_dir:                 'my_datasets/subject1/eval' # save data to this folder
  folder_path:                '/media/lab/Hard Disk' # leave it '' if you read/write data in the current folder,
                                                     # otherwise specify the path (e.g., on hard disk)
  save_data:                  False # {True, False}

  train_mode:                 'eval' # {'train', 'test', 'eval'}
  agent_type:                 'reg' # {'none', 'reg', 'latent', 'endToend'}
  dagger_type:                'none' # {'none', 'vanilla', 'hg'}

  initial_pose:               (0,0,5,0.5)
                              # a set of (pos_x, pos_y, pos_z, yaw) 
                              # Map1: (0,0,5,0), (450,-26,5,0)
                              # Map2: (0,0,5,0), (467,12,5,0)
                              # Map3: (0,0,5,0), (453,7,5,0)
                              # Map4: (0,0,5,0), (458,-11,5,0)
                              # Map5: (0,0,5,0), (315,16,5,0)
                              # Map7: (0,0,5,0), (322,-18,5,0)
                              # Map8: (0,0,5,0), (450,10,5,0)
                              # Map9: (0,0,5,0), (450,25,5,0)
                              # O1: (0,0,5,0), (118,123,5,0)
                              # O2: (1,14,5,0), (118,-123,5,0)
                              # Map10: (0,0,5,0.5),(214,2,5,3)
                              # Map11: (-10,-10,5,0.75),(205,7,5,-3)
                              # Template:(0,0,5,0),(120,143,5,0),(56,66,5,0),(10,49,5,0),(45,112,5,0) 
                              # NH: (115,181,5,0)
  random_start:               False # add small value to the initial pose
                                     
## Controller parameters
ctrl_params:
  max_yawRate:                45.0 # deg/s
  forward_speed:              2.0  # m/s
  mission_height:             5.0  # m
  image_size:                 (480, 640) # (Width, Height)
  use_rangefinder:            False # use rangefinder for terrain following

## RC/Joystick parameters
rc_params:
  device_id:                  0 # device ID
  yaw_axis:                   3 # yaw axis
  mode_axis:                  5 # flight mode axis (e.g., hover, mission)
  type_axis:                  6 # controller type axis (e.g., pilot, agent)
  use_keyboard:               True # use keyboard

## Visualize parameters
visualize_params:
  plot_trajectory:            False # plot a 2D trajectory in a new window
  plot_heading:               False # plot heading in the current window
  plot_cmd:                   True # plot cmd in the current window

## Agent controller parameters
agent_params:
  # Regression
  reg_num_prvs:               0 # number of previous cmd to use
  reg_prvs_mode:              'exponential' # {'exponential', 'linear'} type of prvs cmd
  reg_model_path:             'my_outputs/subject1/iter4/reg/reg_model.pkl' # regression model file path
  
  # Latent NN
  img_resize:                 (64, 64) # resize image before VAE, right now only support (64, 64)
  vae_model_type:             'vanilla_vae' # VAE model type
  vae_model_path:             'my_outputs/VAE64/vanilla_vae/vanilla_vae_model_z_64.pt' # VAE model file path
  latent_model_path:          'my_outputs/subject7/iter3/latent_nn_vanilla_vae/latent_nn_vanilla_vae_model_z_64.pt' # Latent model filepath

  # EndToEnd
  endToend_model_path:        'my_outputs/subject11/iter3/end_to_end/end_to_end_model.pt'

## Evaluation parameters
eval_params:  
  max_counter:                5 # number of evaluation trials 
  max_distance:               210 # maximum x distance for one trail
  show_process_time:          False # print out the processing time
  max_time_counter:           100 # number of time steps used to calculate the processing time