# Simulation parameters
sim_params:
  controller_type:  'expert' # {'expert', 'ling', 'vae'}
  dagger_type:      'vanillar' # {'vanilla-dagger', 'hg-dagger'}
  loop_rate:        10.0 # Hz
  output_path:      'my_datasets/test'
  is_save_data:      False # {True, False}
  train_mode:       'test' # {'train', 'test'}

# Controller parameters
ctrl_params:
  max_yawRate:      45.0 # deg/s
  forward_speed:    2.0  # m/s
  height:           5.0  # m
  image_size:       (480, 640) # Width x Height 

# RC/Joystick parameters
rc_params:
  device_id:  0 
  yaw_axis:   3
  mode_axis:  6

# Visualize parameters
visualize_params:
  is_plot_2Dpos: False
  is_plot_heading: True 

# Training parameters
train_params:
  n_epochs: 200
  batch_size: 32
  resize: (64,64)

vae_params:
  latent_dim: 10
  checkpoint_path: 'my_outputs'


# nn_params:
  

# ling_params:






