# Simulation parameters
sim_params:
  controller_type:            'reg' # {'expert', 'reg', 'latent'}
  dagger_type:                'vanillar' # {'vanilla-dagger', 'hg-dagger'}
  loop_rate:                  10.0 # Hz
  output_path:                'my_datasets/test'
  initial_pose:               (0,0,0,0) # {pos_x, pos_y, pos_z, yaw} e.g. (115,181,0,0)
  save_data:                  False # {True, False}
  train_mode:                 'train' # {'train', 'test'}

# Controller parameters
ctrl_params:
  max_yawRate:                45.0 # deg/s
  forward_speed:              2.0  # m/s
  height:                     5.0  # m
  image_size:                 (480, 640) # Width x Height 

# RC/Joystick parameters
rc_params:
  device_id:                  0 
  yaw_axis:                   3
  mode_axis:                  6

# Visualize parameters
visualize_params:
  plot_2Dpos:                 False
  plot_heading:               True 

# Training parameters
train_params:
  dataset_dir:                'my_datasets/test/2021_Jan_27_08_24_26'
  output_dir:                 'my_outputs/test/iter0'
  
  cmd_index:                  6 # column index of yaw command in .csv file
  
  train_reg:                  True
  train_vae:                  False
  train_latent:               False
  result_only:                False # this will disable all trainings and only show results

  z_dim:                      10 # latent dimension
  img_resize:                 (64, 64) # resize image before VAE, right now only support (64, 64)

  reg_weight_filename:        'reg_weight.csv'

  vae_n_epochs:               300
  vae_batch_size:             32
  vae_checkpoint_filename:    'vae_checkpoint.pt'
  vae_checkpoint_preload:     True
  vae_model_filename:         'vae_model.pt'

  latent_n_epochs:            400
  latent_batch_size:          32
  latent_checkpoint_filename: 'latent_checkpoint.pt'
  latent_checkpoint_preload:  True
  latent_model_filename:      'latent_model.pt'