# Simulation parameters
sim_params:
  loop_rate:                  10.0 # Hz
  output_path:                'my_datasets/peng/river/test' # save data to this path
  save_data:                  False # {True, False}

  train_mode:                 'test' # {'train', 'test'}
  agent_type:                 'reg' # {'none', 'reg', 'latent'}
  dagger_type:                'none' # {'none', 'vanilla', 'hg'}

  initial_pose:               (0,0,5,0),(120,143,5,0),(56,66,5,0),(10,49,5,0),(45,112,5,0) 
                              # (0,0,5,0),(120,143,5,0),(56,66,5,0),(10,49,5,0),(45,112,5,0) 
                              # a set of (pos_x, pos_y, pos_z, yaw) 
                              # e.g. (115,181,5,0) in nh
                              
# Controller parameters
ctrl_params:
  max_yawRate:                45.0 # deg/s
  forward_speed:              2.0  # m/s
  mission_height:             5.0  # m
  image_size:                 (480, 640) # Width x Height
  use_rangefinder:            False # use rangefinder for terrain following
  model_path:                 'my_outputs/peng/river/iter0' # model file path

# RC/Joystick parameters
rc_params:
  device_id:                  0 # device ID
  yaw_axis:                   3 # yaw axis
  mode_axis:                  5 # flight mode axis (e.g., hover, mission)
  type_axis:                  6 # controller type axis (e.g., pilot, agent)

# Visualize parameters
visualize_params:
  plot_trajectory:            False # plot a 2D trajectory in a new window
  plot_heading:               False # plot heading in the current window
  plot_cmd:                   True # plot cmd in the current window

# Training parameters
train_params:
  dataset_dir:                'my_datasets/peng/river/iter0' # source datasets path
  output_dir:                 'my_outputs/peng/river/iter0' # save output to this path
  
  result_only:                False # this will diable all the trainings and only display the existing results

  train_reg:                  True # enable train linear regression weights
  preload_sample:             True # preload samples from file
  reg_num_prvs:               5 # number of previous cmd to use
  reg_weight_filename:        'reg_weight.csv' # regression weight file name

  train_vae:                  False # enable train VAE model
  z_dim:                      15 # latent dimension
  img_resize:                 (64, 64) # resize image before VAE, right now only support (64, 64)
  vae_n_epochs:               200 # number of epochs
  vae_batch_size:             32 # batch size
  vae_checkpoint_filename:    'vae_checkpoint_z_15.pt' # checkpoint file name
  vae_checkpoint_preload:     False # preload a VAE checkpoint
  vae_model_filename:         'vae_model_z_15.pt' # save VAE model to this file name
  vae_learning_rate:          0.001 # learning rate

  train_latent:               False  # enable train latent controller network model
  latent_n_epochs:            200 # number of epochs
  latent_batch_size:          32 # batch size
  latent_checkpoint_filename: 'latent_checkpoint_z_15.pt' # latent controller checkpoint file name
  latent_checkpoint_preload:  True # preload a latent controller checkpoint
  latent_model_filename:      'latent_model_z_15.pt' # save latent controller model to this file name
  latent_num_prvs:            5 # number of previous cmd to use
  latent_learning_rate:       0.001 # learning rate
