# Simulation parameters
sim_params:
  loop_rate:        15.0    # Hz
  max_yawRate:      45.0    # deg/s
  forward_speed:    1.5     # m/s
  height:           5.0     # m
  image_size:       (480, 640) # Width x Height 
  controller_type:  'expert'       #
  dagger_type:      'vanillar'     #
  is_train: False #

# RC/Joystick parameters
rc_params:
  device_id:  0 
  yaw_axis:   3
  speed_axis: 5
  mode_axis:  5

# Visualize parameters
visualize_params:
  plot_2Dpos: False
  plot_heading: True

# Training parameters
train_params:
  n_epochs: 200
  batch_size: 32
  resize: (64,64)

vae_params:
  latent_dim: 10
  checkpoint_path: 'my_outputs'


# nn_params:
  

# ling_params:






